version: '3.8'

services:
  database:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network
    ports:
      - "5432:5432"

  backend:
    container_name: api
    build:
      context: ./api
    networks:
      - my-network
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    container_name: web
    build:
      context: ./web
    networks:
      - my-network
    ports:
      - "3000:3000"
    depends_on:
    - backend

volumes:
  db-data:

networks:
  my-network:
