version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    # environment:
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_USER: myuser
    #   DB_PASSWORD: mypass
    #   DB_NAME: mydb
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data:
